version: "3.8"
services: 
    server:
        image: node:14
        environment: 
            - PORT=8080
        volumes:
            - type: bind
              source: ./server/
              target: /usr/src/app
            - type: volume
              source: nodemodules # name of the volume, see below
              target: /usr/src/app/node_modules
              volume:
                nocopy: true
            - type: volume
              source: sshpublic
              target: /usr/src/app/ssh_public
              volume:
                nocopy: true
        working_dir: /usr/src/app
        command: > 
                  sh -c "./entrypoint.sh && 
                         npm install -g nodemon &&
                         npm install &&
                         npm run dev" 
        ports: 
            - "8080:8080"
        networks:
          net:
            aliases:
              - server
    ffmpeg: 
        depends_on: 
          - server
        build: ./ffmpeg
        tty: true
        networks:
          net:
            aliases:
              - ffmpeg
        volumes:
          - type: volume
            source: sshpublic
            target: /usr/local/ssh_public
            volume:
              nocopy: true
        # command: ./entrypoint.sh
      #   devices: "=========DEVICE NAME:dddd"
      #   volumes:
      #     - type: bind
      #       source: /path/to/libDeckLinkAPI.so
      #       target: /usr/lib/libDeckLinkAPI.so
volumes: 
    nodemodules:
    sshpublic:

networks: 
  net: